from lib2cubs.applevelcom.basic import RemoteBase


class Remote(RemoteBase):

	def server_info(self) -> dict: ...
	def server_time(self) -> str: ...
	def services_list(self) -> list: ...
	def service_status(self, services: str or list) -> dict: ...
	def service_start(self, services: str or list) -> bool: ...
	def service_stop(self, services: str or list) -> bool: ...
	def service_disable(self, services: str or list) -> bool: ...
	def service_enable(self, services: str or list) -> bool: ...
	def service_config(self, service: str) -> dict or False: ...
